name: mp-env
channels:
  - conda-forge
dependencies:
  # System related
  - python=3.8
  - pip
  - build
  - ipykernel
  - ipywidget
  - gcsfs
  - pyyaml
  - types-pyyaml
  # API
  - fastapi
  - uvicorn
  - python-multipart
  - httpx
  # Scipy stack
  - numpy
  - matplotlib
  - scikit-learn
  - pandas
  # CV
  - opencv
  # Others
  - tqdm
  # Testing
  - pytest
  - pytest-cov
  - pytest-mock
  # Formating, linting
  - mypy
  - pylint
  - black
  - isort
  - pip:
    - mediapipe